version: "3.7"

services:
    application:
        restart: on-failure
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: app-dev
        volumes:
            - ".:/app"
        ports:
            - "8001:8000"
        env_file:
            - docker/dev.env
        depends_on:
            - database

    database:
        restart: on-failure
        image: postgres:11-alpine
        volumes:
            - "./docker/database:/docker-entrypoint-initdb.d/:ro"
        environment:
            POSTGRES_DB: "app"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
