namespace: iabwww
labels:
  - pairs:
      app.kubernetes.io/part-of: iabwww
      io.portainer.kubernetes.application.stack: iabwww
    includeTemplates: true
configMapGenerator:
  - name: iabwww-files-cfgmap
    files:
      - local.py
      - supervisord.conf
      - nginx-default.conf
      - nginx.conf
resources:
  - memcached.yaml
  - wagtail.yaml
  - cron.yaml
